background = 0xFF191724
base = 0xFF26233A
text = 0xFFE0DEF4
alternate_base = 0xFF21202E
bright_text = 0xFFC4A7E7
accent = 0xFFC4A7E7
link_text = 0xFFC4A7E7
accent_secondary = 0xFFEBBCBA
font_family = "IBM Plex Mono"
font_family_monospace = "monospace"
font_size = 13
small_font_size = 10
rounding_large = 8
rounding_small = 4
