# theme: rose-pine
background              #191724
foreground              #E0DEF4
cursor                  #E0DEF4
cursor_text_color       #191724
selection_foreground    #E0DEF4
selection_background    #403D52
active_tab_background   #26233A
active_tab_foreground   #C4A7E7
inactive_tab_background #26233A
inactive_tab_foreground #6E6A86

background_opacity 0.90

color0  #191724
color1  #EB6F92
color2  #31748F
color3  #F6C177
color4  #9CCFD8
color5  #C4A7E7
color6  #9CCFD8
color7  #E0DEF4
color8  #6E6A86
color9  #EB6F92
color10 #31748F
color11 #F6C177
color12 #9CCFD8
color13 #C4A7E7
color14 #9CCFD8
color15 #FFFFFF
