# Argvus palette
# ---
# bg         "#191724"
# bg-2       "#26233A"
# ui         "#26233A"
# ui-2       "#403D52"
# ui-3       "#403D52"
# tx-3       "#6E6A86"
# tx-2       "#908CAA"
# tx         "#E0DEF4"
# red-400     "#EB6F92" re
# orange-400  "#F6C177" or
# yellow-400  "#908CAA" ye
# yellow-600  "#F6C177" ye-2
# green-400   "#C4A7E7" gr
# cyan-400    "#C4A7E7" cy
# cyan-600    "#2E2E2E" cy-2
# cyan-700    "#2E2E2E" cy-700
# cyan-900    "#26233A" cy-900
# blue-400    "#C4A7E7" bl
# purple-400  "#8A8A8A" pu
# magenta-400 "#EB6F92" ma

[app]
overall = { bg = "#191724" } # bg

[mgr]
cwd = { fg = "#E0DEF4", bold = true } # tx

# Find
find_keyword = { fg = "#C4A7E7", reversed = true } # cy
find_position = { fg = "#C4A7E7", bold = true, italic = true } # cy

# Marker
marker_copied = { fg = "#C4A7E7", bg = "#C4A7E7" } # gr, gr
marker_cut = { fg = "#EB6F92", bg = "#EB6F92" } # re, re
marker_marked = { fg = "#2E2E2E", bg = "#2E2E2E" } # cy-700, cy-700
marker_selected = { fg = "#C4A7E7", bg = "#C4A7E7" } # cy, cy

# Count
count_copied = { fg = "#C4A7E7", bold = true, reversed = true } # gr
count_cut = { fg = "#EB6F92", bold = true, reversed = true } # re
count_selected = { fg = "#C4A7E7", bold = true, reversed = true } # cy

# Border
border_symbol = "│"
border_style = { fg = "#26233A" } # ui

[indicator]
parent = { underline = true }
current = { fg = "#E0DEF4", bg = "#26233A" } # tx, ui
preview = { underline = true }
padding = { open = "█", close = "█" }

[tabs]
active = { fg = "#E0DEF4", bg = "#403D52", bold = true } # tx, ui-3
inactive = { fg = "#908CAA", bg = "#26233A" } # tx-2, ui
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
# Normal mode
normal_main = { fg = "#E0DEF4", bg = "#403D52", bold = true } # tx, ui-3
normal_alt = { fg = "#908CAA", bg = "#26233A" } # tx-2, ui

# Select mode
select_main = { fg = "#191724", bg = "#C4A7E7", bold = true } # bg, cy
select_alt = { fg = "#C4A7E7", bg = "#26233A" } # cy, cy-900

# Unset mode
unset_main = { fg = "#191724", bg = "#C4A7E7", bold = true } # bg, cy
unset_alt = { fg = "#C4A7E7", bg = "#26233A" } # cy, cy-900

[status]
overall = { fg = "#E0DEF4" } # tx

# Permissions
perm_type = { fg = "#C4A7E7" } # bl
perm_read = { fg = "#908CAA" } # ye
perm_write = { fg = "#EB6F92" } # re
perm_exec = { fg = "#C4A7E7" } # gr
perm_sep = { fg = "#908CAA" } # tx-2

# Progress
progress_label = { fg = "#191724" } # bg
progress_normal = { fg = "#C4A7E7", bg = "#2E2E2E" } # cy, cy-700
progress_error = { bg = "#EB6F92" } # re

[which]
cols = 3
mask = { bg = "#26233A" } # bg-2
cand = { fg = "#C4A7E7", bold = true } # cy
rest = { fg = "#C4A7E7", italic = true } # cy
desc = { fg = "#6E6A86" } # tx-3
separator = " "
separator_style = { }

[confirm]
border = { fg = "#403D52" } # ui-3
title = { fg = "#6E6A86", bold = true } # tx-3
body = { fg = "#E0DEF4", bold = true } # tx
list = { fg = "#E0DEF4" } # tx
btn_yes = { fg = "#E0DEF4", bg = "#403D52", bold = true } # tx, ui-3
btn_no = { fg = "#908CAA", bg = "#26233A" } # tx-2, ui

[spot]
border = { fg = "#403D52" } # ui-3
title = { fg = "#6E6A86", bold = true } # tx-3
tbl_col = { fg = "#908CAA" } # tx-2
tbl_cell = { fg = "#E0DEF4", bg = "#26233A" } # tx, ui

[notify]
# Notification title
title_info = { fg = "#C4A7E7" } # bl
title_warn = { fg = "#F6C177" } # or
title_error = { fg = "#EB6F92" } # re

[pick]
border = { fg = "#403D52", bold = true } # ui-3
active = { fg = "#E0DEF4" } # tx
inactive = { fg = "#908CAA" } # tx-2

[input]
border = { fg = "#403D52" } # ui-3
title = { fg = "#6E6A86", bold = true } # tx-3
value = { fg = "#E0DEF4" } # tx
selected = { bg = "#26233A" } # bg-2

[cmp]
border = { fg = "#403D52", bold = true } # ui-3
active = { fg = "#E0DEF4", bg = "#26233A" } # tx, ui
inactive = { fg = "#908CAA" } # tx-2

[tasks]
border = { fg = "#403D52" } # ui-3
title = { fg = "#6E6A86", bold = true } # tx-3
hovered = { fg = "#E0DEF4", bg = "#26233A" } # tx, ui

[help]
on = { fg = "#C4A7E7" } # bl
run = { fg = "#C4A7E7" } # cy
desc = { fg = "#6E6A86", italic = true } # tx-3
hovered = { bg = "#26233A" } # ui
footer = { fg = "#191724", bg = "#C4A7E7", bold = true } # bg, cy

[filetype]
rules = [
  # Empty files
  { mime = "inode/empty", fg = "#6E6A86" }, # tx-3

  # Special files
  { url = "*", is = "orphan", fg = "#6E6A86" }, # tx-3
  { url = "*/", is = "orphan", fg = "#6E6A86" }, # tx-3
  { url = "*", is = "link", fg = "#C4A7E7" }, # cy
  { url = "*/", is = "link", fg = "#C4A7E7" }, # cy
  { url = "*", is = "block", fg = "#E0DEF4" }, # tx
  { url = "*", is = "char", fg = "#E0DEF4" }, # tx
  { url = "*", is = "fifo", fg = "#EB6F92" }, # ma
  { url = "*", is = "sock", fg = "#EB6F92" }, # ma
  { url = "*", is = "sticky", fg = "#E0DEF4" }, # tx
  { url = "*", is = "dummy", fg = "#6E6A86" }, # tx-3

  # Fallback
  { url = "*/", fg = "#E0DEF4" }, # tx
  { url = "*", is = "exec", fg = "#C4A7E7" }, # gr
  { url = "*", fg = "#908CAA" } # tx-2
]

[icon]
dirs = [
  { name = ".config", text = "", fg = "#C4A7E7" }, # cy
  { name = ".git", text = "", fg = "#C4A7E7" }, # cy
  { name = ".github", text = "", fg = "#C4A7E7" }, # cy
  { name = ".npm", text = "", fg = "#C4A7E7" }, # cy
  { name = "Desktop", text = "", fg = "#C4A7E7" }, # cy
  { name = "Development", text = "", fg = "#C4A7E7" }, # cy
  { name = "Documents", text = "", fg = "#C4A7E7" }, # cy
  { name = "Downloads", text = "", fg = "#C4A7E7" }, # cy
  { name = "Library", text = "", fg = "#C4A7E7" }, # cy
  { name = "Movies", text = "", fg = "#C4A7E7" }, # cy
  { name = "Music", text = "", fg = "#C4A7E7" }, # cy
  { name = "Pictures", text = "", fg = "#C4A7E7" }, # cy
  { name = "Public", text = "", fg = "#C4A7E7" }, # cy
  { name = "Videos", text = "", fg = "#C4A7E7" } # cy
]
conds = [
  # Special files
  { if = "orphan", text = "", fg = "#6E6A86" }, # tx-3
  { if = "link", text = "", fg = "#C4A7E7" }, # cy
  { if = "block", text = "", fg = "#E0DEF4" }, # tx
  { if = "char", text = "", fg = "#E0DEF4" }, # tx
  { if = "fifo", text = "", fg = "#EB6F92" }, # ma
  { if = "sock", text = "", fg = "#EB6F92" }, # ma
  { if = "sticky", text = "", fg = "#E0DEF4" }, # tx
  { if = "dummy", text = "", fg = "#6E6A86" }, # tx-3

  # Fallback
  { if = "dir", text = "", fg = "#C4A7E7" }, # cy
  { if = "exec", text = "", fg = "#C4A7E7" }, # gr
  { if = "!dir", text = "", fg = "#908CAA" } # tx-2
]